heat_template_version: pike

description: >
  OpenStack containerized Congress API service

parameters:
  DockerNamespace:
    description: namespace
    default: 'tripleoupstream'
    type: string
  DockerCongressApiImage:
    description: image
    default: 'centos-binary-congress-api:latest'
    type: string
  DockerCongressConfigImage:
    description: image
    default: 'centos-binary-congress-api:latest'
    type: string
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json

resources:

  ContainersCommon:
    type: ./containers-common.yaml

  CongressApiBase:
    type: ../../puppet/services/congress.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      RoleName: {get_param: RoleName}
      RoleParameters: {get_param: RoleParameters}

outputs:
  role_data:
    description: Role data for the Congress API role.
    value:
      service_name: {get_attr: [CongressApiBase, role_data, service_name]}
      config_settings:
        map_merge:
          - get_attr: [CongressApiBase, role_data, config_settings]
      step_config: &step_config
        get_attr: [CongressApiBase, role_data, step_config]
      service_config_settings: {get_attr: [CongressApiBase, role_data, service_config_settings]}
      # BEGIN DOCKER SETTINGS
      puppet_config:
        config_volume: congress
        puppet_tags: congress_config
        step_config: *step_config
        config_image:
          list_join:
            - '/'
            - [ {get_param: DockerNamespace}, {get_param: DockerCongressConfigImage} ]
      kolla_config:
        /var/lib/kolla/config_files/congress_api.json:
          command: /usr/bin/congress-server --config-file=/etc/congress/congress.conf --log-file=/var/log/congress/api.log
          permissions:
            - path: /var/log/congress
              owner: congress:congress
              recurse: true
      docker_config:
        # db sync runs before permissions set by kolla_config
        step_3:
          congress_init_logs:
            start_order: 0
            image: &congress_image
              list_join:
                - '/'
                - [ {get_param: DockerNamespace}, {get_param: DockerCongressApiImage} ]
            privileged: false
            user: root
            volumes:
              - /var/log/containers/congress:/var/log/congress
            command: ['/bin/bash', '-c', 'chown -R congress:congress /var/log/congress']
          congress_db_sync:
            start_order: 1
            image: *congress_image
            net: host
            privileged: false
            detach: false
            user: root
            volumes:
              list_concat:
                - {get_attr: [ContainersCommon, volumes]}
                -
                  - /var/lib/config-data/congress/etc/:/etc/:ro
                  - /var/log/containers/congress:/var/log/congress
            command: "/usr/bin/bootstrap_host_exec congress su congress -s /bin/bash -c 'congress-db-manage --config-file /etc/congress/congress.conf upgrade head'"
        step_4:
          congress_api:
            start_order: 15
            image: *congress_image
            net: host
            privileged: false
            restart: always
            volumes:
              list_concat:
                - {get_attr: [ContainersCommon, volumes]}
                -
                  - /var/lib/kolla/config_files/congress_api.json:/var/lib/kolla/config_files/config.json:ro
                  - /var/lib/config-data/congress/etc/congress/:/etc/congress/:ro
                  - /var/log/containers/congress:/var/log/congress
            environment:
              - KOLLA_CONFIG_STRATEGY=COPY_ALWAYS
      host_prep_tasks:
        - name: create persistent logs directory
          file:
            path: /var/log/containers/congress
            state: directory
      upgrade_tasks:
        - name: Stop and disable congress_api service
          tags: step2
          service: name=openstack-congress-server state=stopped enabled=no
